### ISSUE TITLE
Table of Contents Plugin Not Working in Multilingual Mode

### ISSUE THREAD

**Issue by Fledardev** [nivianh/toc#7] opened 2024-08-29 14:02 UTC
Hello,

I am experiencing an issue with the Table of Contents plugin in Botble CMS. The plugin works correctly when using the default language of the site, but it does not generate the Table of Contents for translated versions of the pages.

Steps to Reproduce the Issue:

- Install and activate the Table of Contents plugin.
- Create a page with content in the default language (e.g., English).
- Verify that the Table of Contents is generated and displayed correctly.
- Add a translation of this page in another language (e.g., French).
- Access the translated page and observe that the Table of Contents is not displayed.
- Expected Behavior: The Table of Contents should be generated and displayed correctly for all languages, including the translated versions of the pages.

Actual Behavior: The Table of Contents is only displayed for the default language and does not work for translated pages.

Thank you in advance for your help and any fix you may provide.

**Comment by nivianh** [comment] 2024-08-30 02:21
@Fledardev 
I tested and it still works with multi language
You can copy the content in default language to another language to make sure it doesn't show

**Comment by hubfld** [comment] 2024-09-02 05:26
Hello nivianh,

Thank you for your response.

I have confirmed that the "Table of Contents" plugin works correctly on Botble CMS in a standard multilingual environment. However, I noticed that the issue occurs specifically with the [Apexa - Multipurpose Business Consulting Laravel Script](https://codecanyon.net/item/apexa-multipurpose-business-consulting-laravel-script/52857686) theme that I am using.

Could you please assist me in further investigating the origin of the problem? I am looking for any insights or elements that might explain why the Table of Contents is not displaying on translated pages with this particular theme.

Thank you in advance for your help.

Best regards,

**Comment by nivianh** [comment] 2024-09-03 06:16
> Hello nivianh,
> 
> Thank you for your response.
> 
> I have confirmed that the "Table of Contents" plugin works correctly on Botble CMS in a standard multilingual environment. However, I noticed that the issue occurs specifically with the [Apexa - Multipurpose Business Consulting Laravel Script](https://codecanyon.net/item/apexa-multipurpose-business-consulting-laravel-script/52857686) theme that I am using.
> 
> Could you please assist me in further investigating the origin of the problem? I am looking for any insights or elements that might explain why the Table of Contents is not displaying on translated pages with this particular theme.
> 
> Thank you in advance for your help.
> 
> Best regards,

@Fledardev 
I don't have Apexa script to check

**Comment by hubfld** [comment] 2024-09-04 06:24
Hello,

Thank you for your response. Given this, I was wondering if there are any other possible ways we could analyze and address the situation?

Could you provide any suggestions or insights on specific areas to investigate or tests that could help diagnose the issue, especially with the translated pages? Any assistance or recommendations from your side would be greatly appreciated to help move forward with resolving this problem.

Thank you again for your support.

Best regards,

**Comment by nivianh** [comment] 2024-09-04 06:35
> Hello,
> 
> Thank you for your response. Given this, I was wondering if there are any other possible ways we could analyze and address the situation?
> 
> Could you provide any suggestions or insights on specific areas to investigate or tests that could help diagnose the issue, especially with the translated pages? Any assistance or recommendations from your side would be greatly appreciated to help move forward with resolving this problem.
> 
> Thank you again for your support.
> 
> Best regards,

@Fledardev 
You can disable each plugin on Apexa to check the operation of the table of contents

**Comment by hubfld** [comment] 2024-09-05 06:14
Hi @nivianh ,

Apexa theme developers have tested the plugin and identified the issue. It appears that when the '_**dynamic_sidebar**_' function is called within a Blade view file, the table of contents fails to display. This seems to be the root cause of the problem.

**Closed as completed** 2024-09-05 06:38 UTC

**Comment by dinhquochan** [comment] 2024-09-05 08:29
@nivianh I believe this is a bug in the Botble core. Specifically, when `dynamic_sidebar` is called, the Macro cannot be applied. @sangnguyenplus, could you help us investigate why the Macro in the model doesn't work when applied to the `dynamic_sidebar`?

cc @Fledardev

**Comment by nivianh** [comment] 2024-09-05 08:41
`add_action(BASE_ACTION_PUBLIC_RENDER_SINGLE, [$this, 'addToCContent'], 56, 2);`

@dinhquochan
toc add Macro when `BASE_ACTION_PUBLIC_RENDER_SINGLE` is called,

This action may not be called in `dynamic_sidebar`

**Comment by dinhquochan** [comment] 2024-09-05 08:43
Yeah, I know, but when removing `dynamic_sidebar` in the blade file, it works perfectly 😆 It's really weird.

**Comment by hubfld** [comment] 2024-09-06 06:15
Hi @sangnguyenplus,

Have you had a chance to take a look at this issue?

Thanks in advance for your help!
